#! /usr/bin/env bash
#
#	Version of _solo script designed to be embedded in the GemStone product tree.
# Expect extent0.rowan.dbf (solo extent) to be found in $GEMSTNE/bin
#
#	Expected script command line:
#		script [ <script-args> ] [ -- <topaz-command-line-args> ]
#
#
# set -x 

set -e

scriptFile=$1
shift
if [ "$GEMSTONE"x = "x' ] ; then
	echo "Environment variable GEMSTONE must be defined"
	exit 1
fi
GEM_SOLO_EXTENT="$GEMSTONE/bin/extent0.rowan.dbf"
if [ "$ROWAN_PROJECTS_HOME"x = "x" ] ; then
	export ROWAN_PROJECTS_HOME="$GEMSTONE/upgrade/projects"
fi

export SUPERDOIT_DIR="$ROWAN_PROJECTS_HOME/superDoit"
gemstoneDir="$SUPERDOIT_DIR/gemstone"

skip="skip"
if [ "$skip"x = "x" ] ; then
	echo "script file: $scriptFile"
	echo "script args: $*"
	echo "======================"
	# exit 0
fi

$GEMSTONE/bin/topaz -l \
	-I "$gemstoneDir/topazini_solo" \
	-C "GEM_SOLO_EXTENT=$GEM_SOLO_EXTENT" \
	-q \
	-S $gemstoneDir/superdoit.tpz -- $scriptFile -- $*
